version: "3.7"

services:
    app:
        build: ./NODEJS/
        container_name: app
        ports:
           - 3000:3000
        volumes:
            - type: bind
              source: ./dist
              target: /api/dist
            - type: bind
              source: ./NODEJS/api
              target: /copia
        environment:
          - NODE_UID=${NODE_UID}
          - NODE_GID=${NODE_GID}
        command: npm start
        networks:
            - tarea

networks:
    tarea:
        driver: bridge